services:
  - type: web
    name: cycloneguard-api
    runtime: docker
    dockerfilePath: ./docker/backend.Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cycloneguard-db
          property: connectionString

  - type: pserv
    name: cycloneguard-db
    runtime: postgresql
    ipAllowList: []
    plan: free
