from __future__ import annotations

from typing import Literal

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.orm import Session, joinedload

from ml.features import ASSET_TYPES

from ..database import get_db
from ..models import Alert, Infrastructure, as_utc
from ..security import require_admin
from ..services import alert_engine
from .common import data_label, ensure_run, resolve_cyclone

router = APIRouter(prefix="/api/alerts", tags=["alerts"])
SEV = {"critical": 0, "warning": 1, "advisory": 2}


def _alert_dict(al: Alert) -> dict:
    return {"id": al.id, "rule": al.rule, "severity": al.severity, "title": al.title, "message": al.message,
            "location": al.location, "district": al.asset.district, "asset_id": al.asset_id,
            "infrastructure": al.asset.name, "asset_type": al.asset.asset_type,
            "asset_type_label": ASSET_TYPES[al.asset.asset_type]["label"], "lat": al.asset.lat, "lon": al.asset.lon,
            "risk_score": al.risk_score, "confidence": al.confidence, "main_hazard": al.main_hazard,
            "recommended_action": al.recommended_action, "triggered_rules": al.triggered_rules,
            "acknowledged": al.acknowledged, "created_at": as_utc(al.created_at).isoformat()}


@router.get("")
def list_alerts(cyclone_id: int | None = None, severity: Literal["critical", "warning", "advisory"] | None = None,
                district: str | None = None, include_acknowledged: bool = True, db: Session = Depends(get_db)):
    cy = resolve_cyclone(db, cyclone_id)
    run = ensure_run(db, cy)
    stmt = (select(Alert).join(Infrastructure).options(joinedload(Alert.asset)).where(Alert.model_run_id == run.id))
    if severity:
        stmt = stmt.where(Alert.severity == severity)
    if district:
        stmt = stmt.where(Infrastructure.district == district)
    if not include_acknowledged:
        stmt = stmt.where(Alert.acknowledged.is_(False))
    alerts = sorted(db.scalars(stmt).all(), key=lambda a: (SEV[a.severity], -a.risk_score))
    counts = {s: sum(1 for a in alerts if a.severity == s) for s in SEV}
    return {"cyclone_id": cy.id, **data_label(cy), "counts": counts, "items": [_alert_dict(a) for a in alerts],
            "note": "Alerts are generated by transparent rules on model estimates; they do not confirm damage."}


@router.get("/rules")
def alert_rules():
    return alert_engine.rules_catalog()


@router.post("/{alert_id}/acknowledge", dependencies=[Depends(require_admin)])
def acknowledge(alert_id: int, db: Session = Depends(get_db)):
    al = db.get(Alert, alert_id)
    if al is None:
        raise HTTPException(404, detail="alert not found")
    al.acknowledged = True
    db.commit()
    return _alert_dict(al)
